### ISSUE TITLE
Modifiers on before and after

### ISSUE THREAD

**Issue by emaiax** [thoughtbot/climate_control#17]
I have lots of different specs that are using the same ENV var and I wish I didn't need to duplicate all `ClimateControl.modify` for all of those, just because I set up lots of them on `before(:all)` and `around(:each)` runs after that.

Maybe if there's someway to modify all my ENV vars and clean it back on `after(:all)`. The same goes to `before/after (:each)`.

WDYT? I'd be happy to try it out and send you a PR. :)

**Comment by tvon** [comment]
I'm not a dev here, but I think this issue might fall into the domain of the test suite.  E.g. with rspec you can use user-defined metadata and an "around" block in the rspec configuration to setup tests with a specific tag.  [Here is an example of accessing the test metadata in an `around` block](https://www.relishapp.com/rspec/rspec-core/v/3-5/docs/hooks/around-hooks#access-the-example-metadata).
