### ISSUE TITLE
Is it possible to release a new version?

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/climate_control#22]
[This commit](https://github.com/thoughtbot/climate_control/commit/8e51012736ec9b9a4e78e27b075a7e093f14290d) in particular is pretty handy if you forget that you can't set an ENV value to a number.

**Comment by joshuaclayton** [comment]
@mcmire just pushed up 0.0.4, which includes this (and improved thread safety).

Thanks!

**Comment by mcmire** [comment]
❤️
