### ISSUE TITLE
Use another Env hash

### ISSUE THREAD

**Issue by psmod2** [thoughtbot/climate_control#26]
Hi,

In my app, I'm setting my env's using the `appenv` gem and they don't appear under the usual `ENV` object, instead something like `MyApp:Env::my_var`.

Therefore this:
`ClimateControl.modify my_var: 'new value' do`

I tried:

`ClimateControl.modify MyApp:Env::my_var: 'new value' do`

without any luck.

Is it possible to specify that other place for my env variables?

**Comment by mike-burns** [comment]
That's very niche, so we won't support this out of the box.

What you can do is:

```ruby
module MyApp
  class Environment < ClimateControl::Environment
    private
    def env
      MyApp::Env
    end
  end

  class EnvironmentControl
    @@env = Environment.new
    def self.modify(environment_overrides, &block)
      ClimateControl::Modifier.new(env, environment_overrides, &block).process
    end
    def self.env
      @@env
    end
  end
end
```

And then

```ruby
MyApp::EnvironmentControl.modify my_var: 'new value' { ... }
```
