### ISSUE TITLE
SyntaxError in 1.0.0

### ISSUE THREAD

**Issue by kleinjm** [thoughtbot/climate_control#35]
Upon installing the latest version (1.0.0 which came out ~18 days ago) I received the following error.

```
An error occurred while loading ./spec/requests/api/debug_stats_spec.rb.
Failure/Error: require File.expand_path("../config/environment", __dir__)

SyntaxError:
  /Users/jklein/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/climate_control-1.0.0/lib/climate_control/environment.rb:22: syntax error, unexpected keyword_ensure, expecting keyword_end
        ensure
              ^
  /Users/jklein/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/climate_control-1.0.0/lib/climate_control/environment.rb:33: syntax error, unexpected keyword_end, expecting end-of-input
# ./config/application.rb:7:in `<top (required)>'
# ./config/environment.rb:2:in `require'
# ./config/environment.rb:2:in `<top (required)>'
# ./spec/rails_helper.rb:7:in `require'
# ./spec/rails_helper.rb:7:in `<top (required)>'
# ./spec/requests/api/debug_stats_spec.rb:3:in `require'
# ./spec/requests/api/debug_stats_spec.rb:3:in `<top (required)>'
```

I rolled back to `0.1.0` and the error went away.

Rails: 4.2.11.1
Ruby: 2.4.6

**Comment by mateusdeap** [comment]
I got the same weird error running specs with rails 4.0 and ruby 2.3.8

**Comment by JoshCheek** [comment]
This syntax (block-level `ensure`, [here](https://github.com/thoughtbot/climate_control/blob/4cf92235b66170504e05511205fd5c0d8e8a0a01/lib/climate_control/environment.rb#L22)) was not added until Ruby 2.5, as can be seen [here](https://bugs.ruby-lang.org/issues/12906)

Note that all versions prior to 2.6 have been EOL'd ("end of life", meaning they are no longer maintained), and 2.6 is in security maintenance phase and will be EOL'd soon. So it seems reasonable to me to use this syntax. My recommendation would be to update your app to Ruby to 2.7

Screenshot from https://www.ruby-lang.org/en/downloads/
<img width="603" alt="image" src="https://user-images.githubusercontent.com/77495/132783060-4dca888d-f22a-4c9a-bb36-47d808f96eed.png">

**Comment by nickcharlton** [comment]
I would recommend upgrading your Ruby, as @JoshCheek points out — you'll be missing important security updates and these days I'd not expect the process of upgrading to be too prohibitive.

I'm going to close this one.
