### ISSUE TITLE
Nested usage creates a deadlock (ruby 3.1)

### ISSUE THREAD

**Issue by dup2** [thoughtbot/climate_control#46]
When using it in a nested fashion, it creates a deadlock - our CI times out.

Sample code

```ruby
require 'test_helper'

describe Foo do
   around do |test|
     ClimateControl.modify(SMS_DEFAULT_COUNTRY_CODE: nil) do
        test.call
      end
   end

   it "falls back to the environment" do
     ClimateControl.modify(SMS_DEFAULT_COUNTRY_CODE: '++56') do
        expect(Foo.country_code).to eq '++56'
     end
   end
end
```

This used to work with ruby 2.7 but does not work with ruby 3.1.

Is this expected?

**Comment by dorianmariefr** [comment]
Thanks for the report, I will try to fix it tomorrow

**Comment by dorianmariefr** [comment]
I can't reproduce, there are already existing tests for nested usage and they pass without a deadlock, I tried your test case and it passes too https://github.com/thoughtbot/climate_control/pull/47 (I'm on ruby 3.1 but it passes on all supported ruby versions)

**Comment by dup2** [comment]
> Is `Foo.country_code` just `ENV["SMS_DEFAULT_COUNTRY_CODE"]`?

It is actually using `ENV.fetch('SMS_DEFAULT_COUNTRY_CODE', '++41')`

**Comment by dorianmariefr** [comment]
Looks like something is going wrong between minitest-around using Fiber and us using Monitor. I will see if I can fix it next Friday but not sure what I can do about it. That may even be a Ruby bug
