### ISSUE TITLE
Enable support for ENV.fetch

### ISSUE THREAD

**Issue by sofianegargouri** [thoughtbot/climate_control#54]
Rubocop encourages the use of `ENV.fetch` over `ENV[]`, it might be useful to handle that usecase as well: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FetchEnvVar

**Comment by dorianmariefr** [comment]
what do you mean by "handle that usecase"? climate_control works fine with `fetch` or `[]`

**Comment by martinstreicher** [comment]
@sofianegargouri How did you fix your issue?

**Comment by sofianegargouri** [comment]
If I remember well, my class was required through an initializer. Instead, I had to move the require where I needed it
